projects: 
- {name: Lateefsaka.com,        url: 'http://lateefsaka.com', thumbnail: '../img/lateefsaka-thumb.png'      ,year: 2017, role: UI – Web-development}
- {name: SWNS Reporter,         url: 'http://matdisalvo.com', thumbnail: '../img/matdisalvo-thumb.png'      ,year: 2017, role: UI – Web-development }
- {name: Northplains,           url: '',                      thumbnail: '../img/nps-thumb.png'             ,year: 2015, role: Email design & development – marketing design}
- {name: Xinet Documentation,   url: 'http://docs.xinet.com', thumbnail: '../img/xinet-thumb.png'           ,year: 2016, role: UI – web-development}
- {name: Mileanthony UK,        url: 'milesanthony.uk',       thumbnail: '../img/milesanthonyuk-thumb.png'  ,year: 2016, role: landing page design – development}

social-links:
- {name: 'fa fa-dribbble', link: 'https://dribbble.com/samsosina/'}
- {name: 'fa fa-linkedin', link: 'https://www.linkedin.com/in/samsosina/'}
- {name: 'fa fa-github',   link: 'https://github.com/ssosina/'}
- {name: 'fa fa-codepen',  link: 'http://codepen.io/ssosina/'}
